In [ ]:
import numpy as np
import pandas as pd
import sklearn

In [ ]:
df=pd.read_csv('/content/Iris.csv')
df=df.drop(['Id'],axis=1)
df['Species']=df['Species'].map({'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2}).astype(int)
df.sample(10)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
69             5.6           2.5            3.9           1.1        1
28             5.2           3.4            1.4           0.2        0
61             5.9           3.0            4.2           1.5        1
27             5.2           3.5            1.5           0.2        0
79             5.7           2.6            3.5           1.0        1
39             5.1           3.4            1.5           0.2        0
132            6.4           2.8            5.6           2.2        2
62             6.0           2.2            4.0           1.0        1
135            7.7           3.0            6.1           2.3        2
121            5.6           2.8            4.9           2.0        2

In [ ]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

#KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=3)  # default k value = 5,  but best k value is 3
knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
y_train.value_counts()

Species
1    41
0    40
2    39
Name: count, dtype: int64

#train performance

In [ ]:
train_ans=knn.predict(x_train)

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
confusion_matrix(y_train,train_ans)

array([[40,  0,  0],
       [ 0, 38,  3],
       [ 0,  3, 36]])

In [ ]:
accuracy_score(y_train,train_ans)

0.95

In [ ]:
print(classification_report(y_train,train_ans))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       0.93      0.93      0.93        41
           2       0.92      0.92      0.92        39

    accuracy                           0.95       120
   macro avg       0.95      0.95      0.95       120
weighted avg       0.95      0.95      0.95       120



#test performance

In [ ]:
y_test.value_counts()

Species
2    11
0    10
1     9
Name: count, dtype: int64

In [ ]:
test_ans=knn.predict(x_test)

In [ ]:
confusion_matrix(y_test,test_ans)

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]])

In [ ]:
print(classification_report(y_test,test_ans))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [ ]:
accuracy_score(y_test,test_ans)

1.0

#checking with own data

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
sl = 1.4
sw = 1.8
pl = 0.04
pw = 0.08

if knn.predict([[sl,sw,pl,pw]])[0]==0:
  print('setosa')
elif knn.predict([[sl,sw,pl,pw]])[0]==1:
  print(f'Versicolor')
else:
  print(f'Verginica')

setosa


#saving knn

In [ ]:
import pickle
with open('Knn.pkl','wb') as f:
  pickle.dump(knn,f)

In [ ]:
with open('/content/Knn.pkl','rb') as f:
  x=pickle.load(f)

In [ ]:
x.predict([[sl,sw,pl,pw]])

array([0])

#KNN TEST JSON

In [ ]:
import json

confusion_matrix() returns a NumPy array → convert to list using .tolist()


classification_report() → use output_dict=True to get dictionary format (instead of string)

accuracy_score() → already a float (JSON supports it)

indent=4 means:

👉 Add 4 spaces for formatting (pretty printing)
👉 Make the JSON file more readable
👉 It does NOT change the data
👉 It only changes the appearance of the file

Without indent  Your JSON file will look like this (single line)

Why 4?

You can use any number:

indent=2
indent=4
indent=8


2 → 2 spaces

4 → 4 spaces (most commonly used)

In [ ]:
# Create performance dictionary
knn_test_performance = {
    "confusion_matrix": confusion_matrix(y_test, test_ans).tolist(),
    "classification_report": classification_report(y_test, test_ans, output_dict=True),
    "accuracy_score": accuracy_score(y_test, test_ans)
}
with open("knn_test_performance.json", "w") as f:
    json.dump(knn_test_performance, f, indent=4)

#best k value

In [ ]:
odd=np.arange(3,51,2)
odd

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35,
       37, 39, 41, 43, 45, 47, 49])

In [ ]:
a=[]
for i in odd:
  knn=KNeighborsClassifier(n_neighbors=i)
  knn.fit(x_train,y_train)
  pred=knn.predict(x_test)
  a.append(accuracy_score(y_test,pred))
a

[1.0,
 1.0,
 0.9666666666666667,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.9666666666666667,
 0.9666666666666667]

In [ ]:
odd[np.argmax(a)]

np.int64(3)

#NAIVE BAYES

In [ ]:
from sklearn.naive_bayes import GaussianNB
nb=GaussianNB()
nb.fit(x_train,y_train)

GaussianNB()

#train performance

In [ ]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
confusion_matrix(y_train,nb.predict(x_train))

array([[40,  0,  0],
       [ 0, 38,  3],
       [ 0,  3, 36]])

In [ ]:
print(classification_report(y_train,nb.predict(x_train)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       0.93      0.93      0.93        41
           2       0.92      0.92      0.92        39

    accuracy                           0.95       120
   macro avg       0.95      0.95      0.95       120
weighted avg       0.95      0.95      0.95       120



In [ ]:
accuracy_score(y_train,nb.predict(x_train))

0.95

#test performance

In [ ]:
confusion_matrix(y_test,nb.predict(x_test))

array([[10,  0,  0],
       [ 0,  9,  0],
       [ 0,  0, 11]])

In [ ]:
print(classification_report(y_test,nb.predict(x_test)))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [ ]:
accuracy_score(y_test,nb.predict(x_test))

1.0

#checking with own data

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
sl = 1.4
sw = 1.8
pl = 0.04
pw = 0.08

if nb.predict([[sl,sw,pl,pw]])[0]==0:
  print('setosa')
elif nb.predict([[sl,sw,pl,pw]])[0]==1:
  print(f'Versicolor')
else:
  print(f'Verginica')

setosa


#saving nb

In [ ]:
import pickle
with open('Nb.pkl','wb') as f:
  pickle.dump(nb,f)

In [ ]:
with open('/content/Nb.pkl','rb') as f:
  m=pickle.load(f)

In [ ]:
m.predict([[sl,sw,pl,pw]])

array([0])

#NAIVE BAYES TEST JSON

In [ ]:
nb_test_ans = nb.predict(x_test)
nb_test_performance = {
    "confusion_matrix": confusion_matrix(y_test, nb_test_ans).tolist(),
    "classification_report": classification_report(y_test, nb_test_ans, output_dict=True),
    "accuracy_score": accuracy_score(y_test, nb_test_ans)
}
with open("nb_test_performance.json", "w") as f:
    json.dump(nb_test_performance, f, indent=4)