In [24]:
import warnings
warnings.filterwarnings('ignore')

In [25]:
import numpy as np
import pandas as pd
import sklearn
import sys
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [26]:
class MINI:

  def __init__(self,d):
    try:

      self.df=pd.read_csv(d)
      self.df=self.df.drop(['Id'],axis=1)
      self.df['Species']=self.df['Species'].map({'Iris-setosa':0,'Iris-versicolor':1,'Iris-virginica':2}).astype(int)
      self.x=self.df.iloc[:,:-1]
      self.y=self.df.iloc[:,-1]
      self.x_train,self.x_test,self.y_train,self.y_test=train_test_split(self.x,self.y,test_size=0.2,random_state=42)
      odd=np.arange(3,51,2)
      a=[]
      for i in odd:
        knn=KNeighborsClassifier(n_neighbors=i)
        knn.fit(self.x_train,self.y_train)
        pred=knn.predict(self.x_test)
        a.append(accuracy_score(self.y_test,pred))
      print(f'best k value {odd[np.argmax(a)]}')

    except Exception as e:
      ms,ty,lin=sys.exc_info()
      print(f'{ms} {ty} {lin.tb_lineno}')

  def knn(self):
    try:
      self.knn_reg=KNeighborsClassifier(n_neighbors=3)  # default k value = 5,  but best k value is 3
      self.knn_reg.fit(self.x_train,self.y_train)
      self.train_ans=self.knn_reg.predict(self.x_train)
      print(f'knn train confusion matrix {confusion_matrix(self.y_train,self.train_ans)}')
      print(f' knn train classification report {classification_report(self.y_train,self.train_ans)}')
      print(f'knn train accuracy {accuracy_score(self.y_train,self.train_ans)}')

      self.test_ans=self.knn_reg.predict(self.x_test)
      print(f'knn test confusion matrix {confusion_matrix(self.y_test,self.test_ans)}')
      print(f' knn test classification report {classification_report(self.y_test,self.test_ans)}')
      print(f'knn test accuracy {accuracy_score(self.y_test,self.test_ans)}')

    except Exception as e:
      ms,ty,lin=sys.exc_info()
      print(f'{ms} {ty} {lin.tb_lineno}')


  def nb(self):
    try:
      self.nb_reg=GaussianNB()  # default k value = 5,  but best k value is 3
      self.nb_reg.fit(self.x_train,self.y_train)
      self.nb_train_ans=self.nb_reg.predict(self.x_train)
      print(f'nb train confusion matrix {confusion_matrix(self.y_train,self.nb_train_ans)}')
      print(f' nb train classification report {classification_report(self.y_train,self.nb_train_ans)}')
      print(f'nb train accuracy {accuracy_score(self.y_train,self.nb_train_ans)}')
      self.nb_test_ans=self.nb_reg.predict(self.x_test)
      print(f'nb test confusion matrix {confusion_matrix(self.y_test,self.nb_test_ans)}')
      print(f' nb test classification report {classification_report(self.y_test,self.nb_test_ans)}')
      print(f'nb test accuracy {accuracy_score(self.y_test,self.nb_test_ans)}')

    except Exception as e:
      ms,ty,lin=sys.exc_info()
      print(f'{ms} {ty} {lin.tb_lineno}')

  def knn_check(self):
    try:
      sl = 1.4
      sw = 1.8
      pl = 0.04
      pw = 0.08
      if self.knn_reg.predict([[sl,sw,pl,pw]])[0]==0:
        print('setosa')
      elif self.knn_reg.predict([[sl,sw,pl,pw]])[0]==1:
        print(f'Versicolor')
      else:
        print(f'Verginica')
    except Exception as e:
      ms,ty,lin=sys.exc_info()
      print(f'{ms} {ty} {lin.tb_lineno}')

  def nb_check(self):
    try:
      sl = 1.4
      sw = 1.8
      pl = 0.04
      pw = 0.08
      if self.nb_reg.predict([[sl,sw,pl,pw]])[0]==0:
        print('setosa')
      elif self.nb_reg.predict([[sl,sw,pl,pw]])[0]==1:
        print(f'Versicolor')
      else:
        print(f'Verginica')
    except Exception as e:
      ms,ty,lin=sys.exc_info()
      print(f'{ms} {ty} {lin.tb_lineno}')


if __name__=="__main__":
  obj=MINI('/content/Iris.csv')
  obj.knn()
  obj.nb()
  obj.knn_check()
  obj.nb_check()


best k value 3
knn train confusion matrix [[40  0  0]
 [ 0 38  3]
 [ 0  3 36]]
 knn train classification report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       0.93      0.93      0.93        41
           2       0.92      0.92      0.92        39

    accuracy                           0.95       120
   macro avg       0.95      0.95      0.95       120
weighted avg       0.95      0.95      0.95       120

knn train accuracy 0.95
knn test confusion matrix [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
 knn test classification report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

knn tes